spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:8083/config-server/
  cloud:
    config:
      profile: dev # Profile to fetch from config server
      name: product-service # Application name (should match the config file prefix)
      label: master # Git branch to use
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

server:
  address: localhost
  port: 8089
  servlet:
    context-path: /product-service
